# budget rules per user by synapse team id
teams:
  '3412678': # ampad-workinggroup
    amount: '2000'
    period: ANNUALLY
    unit: USD
    community_manager_emails:
      - 'sc-support@sagebase.org'
  '3412679': # ampad-portalusers
    amount: '100'
    period: ANNUALLY
    unit: USD
    community_manager_emails:
      - 'sc-support@sagebase.org'
